name: Check the avalability of the self-hosted runner
description: Check the avalability of the self-hosted runner
author: Chiel
inputs:
  runner_cfg_pat:
    description: 'RUNNER_CFG_PAT, which is set in the secrets of the organisation'
    required: true
outputs:
  runs-on:
    description: The `runs-on` variable to use for the workflow
    value: ${{ steps.get-runs-on.outputs.runs-on }}
runs:
  using: "composite"
  steps:
    - run: >
        STATUSSES=$(curl -s
          -H "Accept: application/vnd.github+json"
          -H "Authorization: Bearer ${{ inputs.runner_cfg_pat }}
          https://api.github.com/orgs/socialdatabase/actions/runners | jq '.runners[].status') 
        && 
        if [[ "$STATUSSES" =~ .*"online".* ]]; then
          echo "runs-on=[self-hosted]" >> $GITHUB_OUTPUT
        else echo "runs-on=ubuntu-latest" >> $GITHUB_OUTPUT
      shell: bash
