name: Check for availabilty of self-hosted runner
on: workflow_dispatch
jobs:
  get-runs-on:
    runs-on: ubuntu-latest
    outputs:
      runs-on: ${{ steps.get-runs-on.outputs.runs-on }}
    env:
      RUNNER_CFG_PAT: ${{ secrets.RUNNER_CFG_PAT }}
    steps: 
    - uses: actions/checkout@v3
    - run: |
        STATUSSES=$(curl -s \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer $RUNNER_CFG_PAT" \
          https://api.github.com/orgs/socialdatabase/actions/runners | jq '.runners[].status')
        if [[ "$STATUSSES" =~ .*"online".* ]]; then
          echo "runs-on=[self-hosted]" >> $GITHUB_OUTPUT
        else echo "runs-on=ubuntu-latest" >> $GITHUB_OUTPUT
      id: runs-on