name: Check for availabilty of self-hosted runner
on: workflow_dispatch
jobs:
  get-runs-on:
    runs-on: ubuntu-latest
    outputs:
      runs-on: ${{ steps.get-runs-on.outputs.runs-on }}
    env:
      RUNNER_CFG_PAT: ${{ secrets.RUNNER_CFG_PAT }}
    steps: 
    - uses: actions/checkout@v3
    - run: echo "runs-on=$(./check_runner_available.sh)" >> $GITHUB_OUTPUT
      id: check