name: Check for availabilty of self-hosted runner
on: [push]
jobs:
  get-runs-on:
    runs-on: ubuntu-latest
    steps:
      - uses: socialdatabase/gh-actions-runner/.github/workflows/check-runner-available.yml@main

  test:
    # runs-on: ${{ steps.get-runs-on.outputs.runs-on }}
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ steps.get-runs-on.outputs.runs-on }}

  