name: Check for availabilty of self-hosted runner
on: [push]
jobs:
  get-runs-on:
    runs-on: ubuntu-latest
    steps:
      - uses: socialdatabase/gh-actions-runner@main

  test:
    # runs-on: [ self-hosted, "${{ steps.get-runs-on.outputs.runs-on }}" ]
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ steps.get-runs-on.outputs.runs-on }}

  