name: Check for availabilty of self-hosted runner
on: [push]
jobs:
  get-runs-on:
    runs-on: ubuntu-latest
    steps:
      - uses: socialdatabase/gh-actions-runner@test-workflow
        with:
          # runner_cfg_pat: ${{ secrets.RUNNER_CFG_PAT }}
          runner_cfg_pat: gha_pat***

  test:
    # runs-on: [ self-hosted, "${{ steps.get-runs-on.outputs.runs-on }}" ]
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ secrets.RUNNER_CFG_PAT }}
      - run: echo "${{ steps.get-runs-on.outputs }}"

  