name: Check for availabilty of self-hosted runner
on: [push]
jobs:
  get-runs-on:
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/workflows/check-runner-available.yml

  test:
    runs-on: ${{ steps.get-runs-on.outputs.runs-on }}
    steps:
      - run: echo ${{steps.build.outputs.hash}}

  