name: Check for availabilty of self-hosted runner
on: [push]
jobs:
  get-runs-on:
    runs-on: ubuntu-latest
    steps:
      - uses: socialdatabase/gh-actions-runner@test-workflow
        id: get-runs-on
        with:
          runner_cfg_pat: ${{ secrets.RUNNER_CFG_PAT }}

  test:
    # runs-on: [ "${{ steps.get-runs-on.outputs.runs-on }}" ]
    runs-on: ubuntu-latest
    steps:
      - run: echo "${{ steps.get-runs-on.outputs }}"
      - run: echo "${{ steps.get-runs-on.outputs.runs-on }}"

  